import Head from "next/head";
import { Inter } from "next/font/google";
import DrawerAppBar from "@/components/DrawerAppBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DrawerAppBar></DrawerAppBar>
      <h1 className="home">Home</h1>
    </>
  );
}
